/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/institution_members": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institution_members.id"];
          institution_id?: parameters["rowFilter.institution_members.institution_id"];
          member_id?: parameters["rowFilter.institution_members.member_id"];
          is_privileged?: parameters["rowFilter.institution_members.is_privileged"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["institution_members"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** institution_members */
          institution_members?: definitions["institution_members"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institution_members.id"];
          institution_id?: parameters["rowFilter.institution_members.institution_id"];
          member_id?: parameters["rowFilter.institution_members.member_id"];
          is_privileged?: parameters["rowFilter.institution_members.is_privileged"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institution_members.id"];
          institution_id?: parameters["rowFilter.institution_members.institution_id"];
          member_id?: parameters["rowFilter.institution_members.member_id"];
          is_privileged?: parameters["rowFilter.institution_members.is_privileged"];
        };
        body: {
          /** institution_members */
          institution_members?: definitions["institution_members"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/institution_network_members": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institution_network_members.id"];
          institution_id?: parameters["rowFilter.institution_network_members.institution_id"];
          network_member_id?: parameters["rowFilter.institution_network_members.network_member_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["institution_network_members"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** institution_network_members */
          institution_network_members?: definitions["institution_network_members"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institution_network_members.id"];
          institution_id?: parameters["rowFilter.institution_network_members.institution_id"];
          network_member_id?: parameters["rowFilter.institution_network_members.network_member_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institution_network_members.id"];
          institution_id?: parameters["rowFilter.institution_network_members.institution_id"];
          network_member_id?: parameters["rowFilter.institution_network_members.network_member_id"];
        };
        body: {
          /** institution_network_members */
          institution_network_members?: definitions["institution_network_members"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/institutions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institutions.id"];
          institution_name?: parameters["rowFilter.institutions.institution_name"];
          slug?: parameters["rowFilter.institutions.slug"];
          email?: parameters["rowFilter.institutions.email"];
          phone?: parameters["rowFilter.institutions.phone"];
          business_address?: parameters["rowFilter.institutions.business_address"];
          website_url?: parameters["rowFilter.institutions.website_url"];
          logo_url?: parameters["rowFilter.institutions.logo_url"];
          facebook?: parameters["rowFilter.institutions.facebook"];
          linkedin?: parameters["rowFilter.institutions.linkedin"];
          twitter?: parameters["rowFilter.institutions.twitter"];
          xing?: parameters["rowFilter.institutions.xing"];
          institution_description?: parameters["rowFilter.institutions.institution_description"];
          regions?: parameters["rowFilter.institutions.regions"];
          topics?: parameters["rowFilter.institutions.topics"];
          members?: parameters["rowFilter.institutions.members"];
          privileged_members?: parameters["rowFilter.institutions.privileged_members"];
          institutional_members?: parameters["rowFilter.institutions.institutional_members"];
          supported_by?: parameters["rowFilter.institutions.supported_by"];
          is_network?: parameters["rowFilter.institutions.is_network"];
          created_at?: parameters["rowFilter.institutions.created_at"];
          updated_at?: parameters["rowFilter.institutions.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["institutions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** institutions */
          institutions?: definitions["institutions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institutions.id"];
          institution_name?: parameters["rowFilter.institutions.institution_name"];
          slug?: parameters["rowFilter.institutions.slug"];
          email?: parameters["rowFilter.institutions.email"];
          phone?: parameters["rowFilter.institutions.phone"];
          business_address?: parameters["rowFilter.institutions.business_address"];
          website_url?: parameters["rowFilter.institutions.website_url"];
          logo_url?: parameters["rowFilter.institutions.logo_url"];
          facebook?: parameters["rowFilter.institutions.facebook"];
          linkedin?: parameters["rowFilter.institutions.linkedin"];
          twitter?: parameters["rowFilter.institutions.twitter"];
          xing?: parameters["rowFilter.institutions.xing"];
          institution_description?: parameters["rowFilter.institutions.institution_description"];
          regions?: parameters["rowFilter.institutions.regions"];
          topics?: parameters["rowFilter.institutions.topics"];
          members?: parameters["rowFilter.institutions.members"];
          privileged_members?: parameters["rowFilter.institutions.privileged_members"];
          institutional_members?: parameters["rowFilter.institutions.institutional_members"];
          supported_by?: parameters["rowFilter.institutions.supported_by"];
          is_network?: parameters["rowFilter.institutions.is_network"];
          created_at?: parameters["rowFilter.institutions.created_at"];
          updated_at?: parameters["rowFilter.institutions.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.institutions.id"];
          institution_name?: parameters["rowFilter.institutions.institution_name"];
          slug?: parameters["rowFilter.institutions.slug"];
          email?: parameters["rowFilter.institutions.email"];
          phone?: parameters["rowFilter.institutions.phone"];
          business_address?: parameters["rowFilter.institutions.business_address"];
          website_url?: parameters["rowFilter.institutions.website_url"];
          logo_url?: parameters["rowFilter.institutions.logo_url"];
          facebook?: parameters["rowFilter.institutions.facebook"];
          linkedin?: parameters["rowFilter.institutions.linkedin"];
          twitter?: parameters["rowFilter.institutions.twitter"];
          xing?: parameters["rowFilter.institutions.xing"];
          institution_description?: parameters["rowFilter.institutions.institution_description"];
          regions?: parameters["rowFilter.institutions.regions"];
          topics?: parameters["rowFilter.institutions.topics"];
          members?: parameters["rowFilter.institutions.members"];
          privileged_members?: parameters["rowFilter.institutions.privileged_members"];
          institutional_members?: parameters["rowFilter.institutions.institutional_members"];
          supported_by?: parameters["rowFilter.institutions.supported_by"];
          is_network?: parameters["rowFilter.institutions.is_network"];
          created_at?: parameters["rowFilter.institutions.created_at"];
          updated_at?: parameters["rowFilter.institutions.updated_at"];
        };
        body: {
          /** institutions */
          institutions?: definitions["institutions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          username?: parameters["rowFilter.profiles.username"];
          first_name?: parameters["rowFilter.profiles.first_name"];
          last_name?: parameters["rowFilter.profiles.last_name"];
          email?: parameters["rowFilter.profiles.email"];
          phone?: parameters["rowFilter.profiles.phone"];
          website_url?: parameters["rowFilter.profiles.website_url"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          facebook?: parameters["rowFilter.profiles.facebook"];
          linkedin?: parameters["rowFilter.profiles.linkedin"];
          twitter?: parameters["rowFilter.profiles.twitter"];
          xing?: parameters["rowFilter.profiles.xing"];
          job?: parameters["rowFilter.profiles.job"];
          bio?: parameters["rowFilter.profiles.bio"];
          regions?: parameters["rowFilter.profiles.regions"];
          skilss?: parameters["rowFilter.profiles.skilss"];
          interests?: parameters["rowFilter.profiles.interests"];
          offerings?: parameters["rowFilter.profiles.offerings"];
          looking_for?: parameters["rowFilter.profiles.looking_for"];
          public_fields?: parameters["rowFilter.profiles.public_fields"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          username?: parameters["rowFilter.profiles.username"];
          first_name?: parameters["rowFilter.profiles.first_name"];
          last_name?: parameters["rowFilter.profiles.last_name"];
          email?: parameters["rowFilter.profiles.email"];
          phone?: parameters["rowFilter.profiles.phone"];
          website_url?: parameters["rowFilter.profiles.website_url"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          facebook?: parameters["rowFilter.profiles.facebook"];
          linkedin?: parameters["rowFilter.profiles.linkedin"];
          twitter?: parameters["rowFilter.profiles.twitter"];
          xing?: parameters["rowFilter.profiles.xing"];
          job?: parameters["rowFilter.profiles.job"];
          bio?: parameters["rowFilter.profiles.bio"];
          regions?: parameters["rowFilter.profiles.regions"];
          skilss?: parameters["rowFilter.profiles.skilss"];
          interests?: parameters["rowFilter.profiles.interests"];
          offerings?: parameters["rowFilter.profiles.offerings"];
          looking_for?: parameters["rowFilter.profiles.looking_for"];
          public_fields?: parameters["rowFilter.profiles.public_fields"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          username?: parameters["rowFilter.profiles.username"];
          first_name?: parameters["rowFilter.profiles.first_name"];
          last_name?: parameters["rowFilter.profiles.last_name"];
          email?: parameters["rowFilter.profiles.email"];
          phone?: parameters["rowFilter.profiles.phone"];
          website_url?: parameters["rowFilter.profiles.website_url"];
          avatar_url?: parameters["rowFilter.profiles.avatar_url"];
          facebook?: parameters["rowFilter.profiles.facebook"];
          linkedin?: parameters["rowFilter.profiles.linkedin"];
          twitter?: parameters["rowFilter.profiles.twitter"];
          xing?: parameters["rowFilter.profiles.xing"];
          job?: parameters["rowFilter.profiles.job"];
          bio?: parameters["rowFilter.profiles.bio"];
          regions?: parameters["rowFilter.profiles.regions"];
          skilss?: parameters["rowFilter.profiles.skilss"];
          interests?: parameters["rowFilter.profiles.interests"];
          offerings?: parameters["rowFilter.profiles.offerings"];
          looking_for?: parameters["rowFilter.profiles.looking_for"];
          public_fields?: parameters["rowFilter.profiles.public_fields"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  institution_members: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `institutions.id`.<fk table='institutions' column='id'/>
     */
    institution_id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    member_id: string;
    /** Format: boolean */
    is_privileged?: boolean;
  };
  institution_network_members: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `institutions.id`.<fk table='institutions' column='id'/>
     */
    institution_id: string;
    /**
     * Format: uuid
     * @description Note:
     * This is a Foreign Key to `institutions.id`.<fk table='institutions' column='id'/>
     */
    network_member_id: string;
  };
  institutions: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     * @default extensions.uuid_generate_v4()
     */
    id: string;
    /** Format: character varying */
    institution_name?: string;
    /** Format: character varying */
    slug?: string;
    /** Format: character varying */
    email?: string;
    /** Format: character varying */
    phone?: string;
    /** Format: character varying */
    business_address?: string;
    /** Format: character varying */
    website_url?: string;
    /** Format: character varying */
    logo_url?: string;
    /** Format: character varying */
    facebook?: string;
    /** Format: character varying */
    linkedin?: string;
    /** Format: character varying */
    twitter?: string;
    /** Format: character varying */
    xing?: string;
    /** Format: text */
    institution_description?: string;
    /** Format: ARRAY */
    regions?: unknown[];
    /** Format: ARRAY */
    topics?: unknown[];
    /** Format: ARRAY */
    members?: unknown[];
    /** Format: ARRAY */
    privileged_members?: unknown[];
    /** Format: ARRAY */
    institutional_members?: unknown[];
    /** Format: ARRAY */
    supported_by?: unknown[];
    /** Format: boolean */
    is_network?: boolean;
    /** Format: timestamp with time zone */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
  };
  profiles: {
    /**
     * Format: uuid
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /** Format: text */
    username?: string;
    /** Format: character varying */
    first_name?: string;
    /** Format: character varying */
    last_name?: string;
    /** Format: character varying */
    email?: string;
    /** Format: character varying */
    phone?: string;
    /** Format: character varying */
    website_url?: string;
    /** Format: character varying */
    avatar_url?: string;
    /** Format: character varying */
    facebook?: string;
    /** Format: character varying */
    linkedin?: string;
    /** Format: character varying */
    twitter?: string;
    /** Format: character varying */
    xing?: string;
    /** Format: character varying */
    job?: string;
    /** Format: text */
    bio?: string;
    /** Format: ARRAY */
    regions?: unknown[];
    /** Format: ARRAY */
    skilss?: unknown[];
    /** Format: ARRAY */
    interests?: unknown[];
    /** Format: ARRAY */
    offerings?: unknown[];
    /** Format: ARRAY */
    looking_for?: unknown[];
    /** Format: ARRAY */
    public_fields?: unknown[];
    /** Format: timestamp with time zone */
    created_at?: string;
    /** Format: timestamp with time zone */
    updated_at?: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description institution_members */
  "body.institution_members": definitions["institution_members"];
  /** Format: uuid */
  "rowFilter.institution_members.id": string;
  /** Format: uuid */
  "rowFilter.institution_members.institution_id": string;
  /** Format: uuid */
  "rowFilter.institution_members.member_id": string;
  /** Format: boolean */
  "rowFilter.institution_members.is_privileged": string;
  /** @description institution_network_members */
  "body.institution_network_members": definitions["institution_network_members"];
  /** Format: uuid */
  "rowFilter.institution_network_members.id": string;
  /** Format: uuid */
  "rowFilter.institution_network_members.institution_id": string;
  /** Format: uuid */
  "rowFilter.institution_network_members.network_member_id": string;
  /** @description institutions */
  "body.institutions": definitions["institutions"];
  /** Format: uuid */
  "rowFilter.institutions.id": string;
  /** Format: character varying */
  "rowFilter.institutions.institution_name": string;
  /** Format: character varying */
  "rowFilter.institutions.slug": string;
  /** Format: character varying */
  "rowFilter.institutions.email": string;
  /** Format: character varying */
  "rowFilter.institutions.phone": string;
  /** Format: character varying */
  "rowFilter.institutions.business_address": string;
  /** Format: character varying */
  "rowFilter.institutions.website_url": string;
  /** Format: character varying */
  "rowFilter.institutions.logo_url": string;
  /** Format: character varying */
  "rowFilter.institutions.facebook": string;
  /** Format: character varying */
  "rowFilter.institutions.linkedin": string;
  /** Format: character varying */
  "rowFilter.institutions.twitter": string;
  /** Format: character varying */
  "rowFilter.institutions.xing": string;
  /** Format: text */
  "rowFilter.institutions.institution_description": string;
  /** Format: ARRAY */
  "rowFilter.institutions.regions": string;
  /** Format: ARRAY */
  "rowFilter.institutions.topics": string;
  /** Format: ARRAY */
  "rowFilter.institutions.members": string;
  /** Format: ARRAY */
  "rowFilter.institutions.privileged_members": string;
  /** Format: ARRAY */
  "rowFilter.institutions.institutional_members": string;
  /** Format: ARRAY */
  "rowFilter.institutions.supported_by": string;
  /** Format: boolean */
  "rowFilter.institutions.is_network": string;
  /** Format: timestamp with time zone */
  "rowFilter.institutions.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.institutions.updated_at": string;
  /** @description profiles */
  "body.profiles": definitions["profiles"];
  /** Format: uuid */
  "rowFilter.profiles.id": string;
  /** Format: text */
  "rowFilter.profiles.username": string;
  /** Format: character varying */
  "rowFilter.profiles.first_name": string;
  /** Format: character varying */
  "rowFilter.profiles.last_name": string;
  /** Format: character varying */
  "rowFilter.profiles.email": string;
  /** Format: character varying */
  "rowFilter.profiles.phone": string;
  /** Format: character varying */
  "rowFilter.profiles.website_url": string;
  /** Format: character varying */
  "rowFilter.profiles.avatar_url": string;
  /** Format: character varying */
  "rowFilter.profiles.facebook": string;
  /** Format: character varying */
  "rowFilter.profiles.linkedin": string;
  /** Format: character varying */
  "rowFilter.profiles.twitter": string;
  /** Format: character varying */
  "rowFilter.profiles.xing": string;
  /** Format: character varying */
  "rowFilter.profiles.job": string;
  /** Format: text */
  "rowFilter.profiles.bio": string;
  /** Format: ARRAY */
  "rowFilter.profiles.regions": string;
  /** Format: ARRAY */
  "rowFilter.profiles.skilss": string;
  /** Format: ARRAY */
  "rowFilter.profiles.interests": string;
  /** Format: ARRAY */
  "rowFilter.profiles.offerings": string;
  /** Format: ARRAY */
  "rowFilter.profiles.looking_for": string;
  /** Format: ARRAY */
  "rowFilter.profiles.public_fields": string;
  /** Format: timestamp with time zone */
  "rowFilter.profiles.created_at": string;
  /** Format: timestamp with time zone */
  "rowFilter.profiles.updated_at": string;
}

export interface operations {}

export interface external {}
